#*******************************************************************#
#   THIS CODE IS MY OWN WORK, IT WAS WRITTEN WITHOUT CONSULTING     #
#   A TUTOR OR CODE WRITTEN BY OTHER STUDENTS                       #
#                               - ARJUN LAL                         #
#*******************************************************************#


TARGET=pipesort
CC=gcc -g


.PHONY: cleanall cleanobj gdb

all: $(TARGET)

cleanall: cleanobj
	$(RM) $(TARGET)
